apiVersion: v1
data:
  DB_HOST: 35.232.56.51
  DB_NAME: whiteboxqa
  DB_PASSWORD: Innovapath1
  DB_PORT: "3306"
  DB_USER: whiteboxqa
  EMAIL_PASS: zcylsxvakmvwsxll
  EMAIL_USER: hkinnovapath@gmail.com
  MAIL_FROM: hkinnovapath@gmail.com
  MAIL_PASSWORD: zcylsxvakmvwsxll
  MAIL_PORT: "587"
  MAIL_SERVER: smtp.gmail.com
  MAIL_SSL_TLS: "False"
  MAIL_STARTTLS: "True"
  MAIL_USERNAME: hkinnovapath@gmail.com
  RESET_PASSWORD_URL: http://localhost:3000/reset-password
  SECRET_KEY: 69f19af7f440cef746e7b2af42835c5351fdd4e174c5bcf4307d01e6936edeca
  SMTP_PORT: "587"
  SMTP_SERVER: smtp.gmail.com
  TO_RECRUITING_EMAIL: recruiting@whitebox-learning.com
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: backend-backend-env
  name: backend-env
