apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend-service
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 32467  # Explicitly specify NodePort
  selector:
    io.kompose.service: frontend
  type: NodePort  # Ensure this is set to NodePort